### ISSUE TITLE
Hisuite shows an update, it updates, but....

### ISSUE THREAD

**Issue by SolluxAlpheratz** [ProfessorJTJ/HISuite-Proxy#221] opened 2022-07-18 14:49 UTC
Hi! i did all the steps are on the guide and HiSuite shows me a successfull update, when it restarts i got an eRecovery error saying that my update aren't valid (im trying to install 10.0.0.563 from 10.0.0.365), but it rollbacks to the version is installed on my huawei, it's a P30 Lite NE. (mar-l21b, c431)

**Comment by ProfessorJTJ** [comment] 2022-07-18 17:13
Hi send your Systemupdate.log file, it can be found at

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by SolluxAlpheratz** [comment] 2022-07-18 21:13
[SystemUpdate_20220718_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/9135818/SystemUpdate_20220718_00.log)

Here's the solicited log, also i have to add that, my cust installed on my p30 is 10.0.0.4 but HiSuite proxy shows me a GBCGroup version not match error, but this don't happens on 10.0.0.7 cust

**Comment by ProfessorJTJ** [comment] 2022-07-19 05:49
You're using packages that are invalid and not approved for installation.
now I don't really get it, how have you managed to make hisuite download the packages?
Did you just use offline packages?
Did you no get a warning by hisuite proxy saying the roms are not approved for installation?
From where did you get the packages information? (links and ids?)

And comparing your roms details with the ones available on the website I see that the problem is from your side. be more cautious, get the roms from the website.

https://professorjtj.github.io/

And clearly you haven't read the documents unforunately.
GBCGroup is when cust and base versions do not match.


As your problem is not related to hisuite proxy, I will close the issue.

**Closed by ProfessorJTJ** 2022-07-19 05:49 UTC
